export { default as Home } from './Home/Home'
export { default as FriendsPage } from './Friends/FriendsPage'
export { default as Groups } from './Groups/Groups'
export { default as Collections } from './Collections/Collections'
export { default as Notifications } from './Notifications/Notifications'
export { default as Create } from './Create/Create'
export { default as Profile } from './Profile/Profile'
export { default as More } from './More/More'

export { default as Dashboard } from './Dashboard/Home/Home'
export { default as Notes } from './Dashboard/Notes/NotesPage'
export { default as Activity } from './Dashboard/Activity/ActivityPage'
export { default as Tasks } from './Dashboard/Tasks/TasksPage'
export { default as Document } from './Dashboard/Document/DocumentPage'
export { default as Calender } from './Dashboard/Apps/Calender'
export { default as Calculator } from './Dashboard/Apps/Calculator'
export { default as Kanban } from './Dashboard/Apps/Kanban'